### ISSUE TITLE
Aarch64 build for Raspberry Pi

### ISSUE THREAD

**Issue by dhruvmsheth** [PINTO0309/Open3D-build#2]
Hi @PINTO0309 Thank you for all your work! I wanted to know if there's an Aarch64 build for Raspberry Pi 64bit OS as well? The repository mentions Jetson Nano. If there is, would be really grateful to try it out. Thanks!!

**Comment by PINTO0309** [comment]
I didn't build it because Open3D processing is too heavy for the RaspberryPi specs.

**Comment by PINTO0309** [comment]
https://github.com/isl-org/Open3D/issues/2895#issuecomment-861226833

**Comment by PINTO0309** [comment]
http://www.open3d.org/docs/release/arm.html#raspberry-pi-4

**Comment by dhruvmsheth** [comment]
Thanks for the reply. Yes, I tried to build it from source but encountered many errors so I was hoping to find a prebuilt wheel on Raspberry Pi 64bit for the library.
Thanks, Dhruv
